version: "3.9"

services:
  web:
    build: ./docker/nginx/
    ports:
      - "8080:80"
    volumes_from:
      - app-data
    links:
      - php

  php:
    image: php:7-fpm
    volumes_from:
      - app-data

  app-data:
    image: php:7-fpm
    volumes:
      - .:/var/www/html/
    command: "true"
