version: "3.9"

x-common: &common
  volumes:
    - .:/var/www/html

services:
  frontend:
    <<: *common
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"

  backend:
    <<: *common
    build:
      context: .
      dockerfile: docker/php/Dockerfile
