version: "3.9"

x-common: &common
  volumes:
    - .:/var/www/html

services:
  web:
    <<: *common
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"

  php:
    <<: *common
    build:
      context: .
      dockerfile: docker/php/Dockerfile
