version: "3.9"

x-common: &common
  volumes:
    - .:/var/www/html

services:
  web:
    <<: *common
    build: ./docker/nginx/
    ports:
      - "8080:80"
    links:
      - php

  php:
    <<: *common
    image: php:7-fpm
